### PR TITLE
Update italian translation

### PR DESCRIPTION
**Pull request by Strange-IPmart**
This is my first time and certainly will have done some mess.....be patient.
I hope I have done everything right :)

### CODE REVIEW

**Comment by zamzameir** [comment]
sync your alignment bro :)

**Comment by Strange-IPmart** [comment]
How can i sync allignement?

**Comment by zamzameir** [comment]
you can use notepad to fix it instead of notepad++ and other stuffs.

**Comment by Strange-IPmart** [comment]
Alignment fixed. Thanks ;)

**Comment by BrianValente** [comment]
Please translate this new file:
https://github.com/BrianValente/WAMOD/blob/master/app/src/main/res/values-v1/strings.xml

**Pull request merged**
